routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where we register Staff portal web routes for the ERP. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group.
|
*/
Auth::routes([
  'register' => false, // Register Routes...
  'reset' => false, // Reset Password Routes...
  'verify' => false, // Email Verification Routes...
]);

Route::group(['middleware' =>'guest'],  function () {
    Route::get('/', 'Auth\WelcomeController@welcome')->name('welcome');
    Route::get('wrong', 'Auth\WelcomeController@wrong')->name('wrong');
    Route::get('login', 'Auth\WelcomeController@welcome')->name('login');
    Route::post('/reset/{id}', 'Auth\RegisterController@reset')->name('reset');
    Route::post('/rec_signup', 'Auth\RegisterController@rec_signup')->name('rec_signup');
    Route::get('/signUp/{id}', 'Auth\RegisterController@confirm')->name('signUp');
    Route::post('/signUp/{id}', 'Auth\RegisterController@create');
});
Route::group(['middleware' => ['auth', 'erp.base', 'erp.auth'], 'prefix' => 'admin',  'as' => 'ERP::'], function () { 
# Users Routes
    Route::get('/', 'DashboardController@dash')->name('dash');
    Route::get('/users', 'UsersController@index')->name('users');
    Route::post('/users/roles', 'UsersController@setRoles')->name('user_roles');

    # Roles Routes --No Wire--
    Route::get('/roles', 'RolesController@index')->name('roles');
    Route::get('/roles/create', 'RolesController@create')->name('roles_create');
    Route::post('/roles/create', 'RolesController@store');
    Route::get('/roles/{id}', 'RolesController@show')->name('roles_show');
    Route::get('/roles/{id}/edit', 'RolesController@edit')->name('roles_edit');
    Route::post('/roles/{id}/edit', 'RolesController@update');
    Route::get('/roles/{id}/permissions', 'RolesController@editPermissions')->name('roles_permissions');
    Route::post('/roles/{id}/permissions', 'RolesController@setPermissions');
    Route::get('/roles/{id}/delete', 'SecurityController@confirm')->name('roles_delete');
    Route::post('/roles/{id}/delete', 'RolesController@destroy'); 

    # Permissions Routes --No Wire--
    Route::get('/permissions', 'PermissionsController@index')->name('permissions');
    Route::get('/permissions/create', 'PermissionsController@create')->name('permissions_create');
    Route::post('/permissions/create', 'PermissionsController@store');
    Route::get('/permissions/{id}/edit', 'PermissionsController@edit')->name('permissions_edit');
    Route::post('/permissions/{id}/edit', 'PermissionsController@update');
    Route::get('/permissions/{id}/delete', 'SecurityController@confirm')->name('permissions_delete');
    Route::post('/permissions/{id}/delete', 'PermissionsController@destroy');

    # Wire Routes 
    Route::get('/students', 'StudentsController@index')->name('students');
    Route::get('/faculties', 'FacultiesController@index')->name('faculties');
    Route::get('/cohorts', 'CohortsController@index')->name('cohorts');
    Route::get('/entry_types', 'Entry_typesController@index')->name('entry_types');
    Route::get('/course_parts', 'Course_PartsController@index')->name('course_parts');
    Route::get('/departments', 'DepartmentsController@index')->name('departments');
    Route::get('/subjects', 'SubjectsController@index')->name('subjects');
    Route::get('/courses', 'CoursesController@index')->name('courses');
    Route::get('/disabilities', 'DisabilitiesController@index')->name('disabilities');
    Route::get('/payments', 'PaymentsController@index')->name('payments');
    Route::get('/sem_fees', 'SemfeesController@index')->name('sem_fees');

    # Scholarships Routes
    Route::get('/scholarships', 'ScholarshipsController@index')->name('scholarships');
    Route::get('/scholarships/{id}', 'ScholarshipsController@students')->name('scholar_stud');

     # Programmes Routes --No Wire--
    Route::get('/programmes', 'ProgrammesController@index')->name('programmes');
    Route::get('/programmes/create', 'ProgrammesController@create')->name('programmes_create');
    Route::post('/programmes/create', 'ProgrammesController@store');
    Route::get('/programmes/{id}', 'ProgrammesController@show')->name('programmes_show');
    Route::get('/programmes/{id}/edit', 'ProgrammesController@edit')->name('programmes_edit');
    Route::post('/programmes/{id}/edit', 'ProgrammesController@update');
    Route::get('/programmes/{id}/delete', 'SecurityController@confirm')->name('programmes_delete');
    Route::post('/programmes/{id}/delete', 'ProgrammesController@destroy'); 
     
    # Sem_Courses Routes   --No Wire--
    Route::get('/sem_courses', 'Sem_CoursesController@index')->name('sem_courses');
    Route::get('/sem_courses/create', 'Sem_CoursesController@create')->name('sem_courses_create');
    Route::post('/sem_courses/create', 'Sem_CoursesController@store');
    Route::get('/sem_courses/{id}', 'Sem_CoursesController@show')->name('sem_courses_show');
    Route::get('/sem_courses/{id}/edit', 'Sem_CoursesController@edit')->name('sem_courses_edit');
    Route::post('/sem_courses/{id}/edit', 'Sem_CoursesController@update');
    Route::get('/sem_courses/{id}/delete', 'SecurityController@confirm')->name('sem_courses_delete');
    Route::post('/sem_courses/{id}/delete', 'Sem_CoursesController@destroy');

    # Semesters Routes  --No Wire--
    Route::get('/semesters', 'SemestersController@index')->name('semesters');
    Route::get('/semesters/create', 'SemestersController@create')->name('semesters_create');
    Route::post('/semesters/create', 'SemestersController@store');
    Route::get('/semesters/{id}', 'SemestersController@show')->name('semesters_show');
    Route::get('/semesters/{id}/edit', 'SemestersController@edit')->name('semesters_edit');
    Route::post('/semesters/{id}/edit', 'SemestersController@update');
    Route::get('/semesters/{id}/delete', 'SecurityController@confirm')->name('semesters_delete');
    Route::post('/semesters/{id}/delete', 'SemestersController@destroy');

    # Parts Routes  --No Wire--
    Route::get('/parts', 'PartsController@index')->name('parts');
    Route::get('/parts/create', 'PartsController@create')->name('parts_create');
    Route::post('/parts/create', 'PartsController@store');
    Route::get('/parts/{id}', 'PartsController@show')->name('parts_show');
    Route::get('/parts/{id}/edit', 'PartsController@edit')->name('parts_edit');
    Route::post('/parts/{id}/edit', 'PartsController@update');
    Route::get('/parts/{id}/delete', 'SecurityController@confirm')->name('parts_delete');
    Route::post('/parts/{id}/delete', 'PartsController@destroy');

    # Applicants Routes
    Route::get('/applicants', 'ApplicantsController@index')->name('applicants');
    // Route::get('/applicants/create', 'ApplicantsController@create')->name('applicants_create');
    // Route::post('/applicants/create', 'ApplicantsController@store');
    Route::get('/applicants/{id}/show', 'ApplicantsController@show')->name('applicants_show');
    Route::get('/applicants/{id}/academic', 'ApplicantsController@academic')->name('applicants_academic');
    Route::get('/applicants/{id}/edit', 'ApplicantsController@edit')->name('applicants_edit');    
    // Route::get('/applicants/{id}/delete', 'SecurityController@confirm')->name('applicants_delete');
    // Route::post('/applicants/{id}/delete', 'ApplicantsController@destroy'); 

    # Registrations Routes
    Route::get('/registration', 'RegistrationController@index')->name('reg');
    Route::get('/registration/register', 'RegistrationController@register')->name('register');
    Route::post('/registration/register', 'RegistrationController@store');
    Route::get('/registration/{id}/show', 'RegistrationController@show')->name('reg_show');
    Route::get('/registration/{id}/edit', 'RegistrationController@edit')->name('reg_edit');
    Route::post('/registration/{id}/edit', 'RegistrationController@update');    
    Route::get('/registration/{id}/delete', 'SecurityController@confirm')->name('reg_delete');
    Route::post('/registrations/{id}/delete', 'RegistrationController@destroy'); 

    # Semester classes Routes
    Route::get('/s_class', 'S_classController@index')->name('s_class');
    Route::get('/s_class/ch', 'S_classController@hod')->name('s_class_hod');
    Route::get('/s_class/dn', 'S_classController@dean')->name('s_class_dn');
    Route::get('/s_class/rg', 'S_classController@registry')->name('s_class_reg');
    Route::get('export/{id}', 'S_classController@export')->name('export');
    Route::post('import', 'S_classController@import')->name('import');    
    Route::get('/s_class/{id}/delete', 'SecurityController@confirm')->name('reg_delete');
    Route::post('/s_class/{id}/delete', 'S_classController@destroy');     
    Route::get('/s_class/{state}/{name}/submit', 'SecurityController@confirm')->name('lect_submit');
    Route::post('/s_class/{state}/{name}/submit', 'S_classController@approve_results'); 

     #Billing 
    Route::get('/semester/billing', 'BillingController@index')->name('billing');
    Route::get('/semester/{id}/billing', 'SecurityController@confirm')->name('bill_sem');
    Route::get('/semester/{id}/un_billing', 'SecurityController@confirm')->name('un_bill_sem');
    Route::post('/semester/{id}/billing', 'un_billing@bill'); 
    Route::post('/semester/{id}/un_billing', 'un_billing@un_bill'); 

    # Database CRUD routes
    Route::get('/CRUD', 'CRUDController@index')->name('CRUD');
    Route::get('/CRUD/{table}', 'CRUDController@table')->name('CRUD_table');
    Route::get('/CRUD/{table}/create', 'CRUDController@create')->name('CRUD_create');
    Route::post('/CRUD/{table}/create', 'CRUDController@createRow');
    Route::get('/CRUD/{table}/{id}', 'CRUDController@row')->name('CRUD_edit');

app/Hod.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Hod extends Model implements Auditable
{
        use \OwenIt\Auditing\Auditable;
protected $connection = 'mysql';
    protected $dates = [
        'created_at', 'updated_at',  
    ];
    use SoftDeletes;

    protected $fillable = [
        'staff_id', 'department_id', 'active', 'from_date', 'to_date',
    ];
   
    
    protected $with = ['staff'];
  
    public static function search($search) 
    {
        return empty($search) ? static::query()
        : static::query()->where('name','Like', '%'.$search.'%');
    } 

    public function getFullNameAttribute()
    { 
        return $this->staff->user->fullname;
    }
    
     public function department()
    {
        return $this->belongsTo('App\Department');
    }
     public function staff()
    {
        return $this->belongsTo('App\Staff');
    }

}

app/Http/Controllers/FacultiesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Faculty;
use Auth;
use ERP;
Use Alert;

class FacultiesController extends Controller
{

    public function index()
    {
        ERP::permissionToAccess('faculties.access');

        # Get all the faculties 
        $faculties  = Faculty::all();
        
        # Return the view
        return view('erp/faculties/index', ['faculties' => $faculties ]);
    }

    public function show($id)
    {
        ERP::permissionToAccess('faculties.access');

        # Get the faculty
        $faculty = Faculty::find($id);

        # Return the view
        return view('admin/faculties /show', ['faculty' => $faculty]);
    }

    public function edit($id)
    {
        ERP::permissionToAccess('faculties.access');

        # Check permissions
        ERP::permissionToAccess('faculties.admin');

        # Find the faculty
        $row = Faculty::find($id);
        
        # Get all the data
        $data_index = 'faculties ';
        require('Data/Edit/Get.php');

        # Return the view
        return view('erp/faculties /edit', [
            'row'       =>  $row,
            'fields'    =>  $fields,
            'confirmed' =>  $confirmed,
            'empty'     =>  $empty,
            'encrypted' =>  $encrypted,
            'hashed'    =>  $hashed,
            'masked'    =>  $masked,
            'table'     =>  $table,
            'code'      =>  $code,
            'wysiwyg'   =>  $wysiwyg,
            'relations' =>  $relations,
        ]);
    }

    public function update($id, Request $request)
    {
        ERP::permissionToAccess('faculties.access');

        # Check permissions
        ERP::permissionToAccess('faculties.admin');

        # Find the row
        $row = Faculty::find($id);
       
        # Save the data
        $data_index = 'faculties ';
        require('Data/Edit/Save.php');

        # Return the admin to the users page with a success message
        return redirect()->route('ERP::faculties ')->with('success', 'Faculty Edited');
    }

    public function create()
    {
        ERP::permissionToAccess('faculties.access');

        # Check permissions
        ERP::permissionToAccess('faculties.admin');

        # Get all the data
        $data_index = 'faculties ';
        require('Data/Create/Get.php');


        # Return the view
        return view('erp/faculties /create', [
            'fields'        =>  $fields,
            'confirmed'     =>  $confirmed,
            'encrypted'     =>  $encrypted,
            'hashed'        =>  $hashed,
            'masked'        =>  $masked,
            'permissions'   =>  $permissions,
            'table'         =>  $table,
            'code'          =>  $code,
            'wysiwyg'       =>  $wysiwyg,
            'relations'     =>  $relations,
        ]);
    }

    public function store(Request $request)
    {
        ERP::permissionToAccess('faculties.access');

        # Check permissions
        ERP::permissionToAccess('faculties.admin');

        # create new faculty
        $row = new Faculty;

        # Save the data
        $data_index = 'faculties ';
        require('Data/Create/Save.php');

        # Set the permissions
        $this->setPermissions($row->id, $request);

        # Return the admin to the faculties  page with a success message
        return redirect()->route('ERP::faculties ')->with('success', 'Faculty Created');
    }

    
    public function destroy($id)
    {
        ERP::permissionToAccess('faculties.access');
        
        # Check permissions
        ERP::permissionToAccess('faculties.admin');

        # Select Faculty
        $faculty = ERP::faculty('id', $id);

        
        # Delete Faculty
        $faculty->delete();

        # Redirect the admin
        return redirect()->route('ERP::faculties ')->with('success', 'Deleted');
    }
}

app/Http/Livewire/Erp/Marks/Add.php
<?php

namespace App\Http\Livewire\Erp\Marks;

use Livewire\Component;
use App\SemCourse;
use App\Weight;
use App\Result;

class Add extends Component
{
	public $weight_id;
	public $weights, $sem_cos;

	public function submit() 
	{
		$this->validate([ 
	      'weight_id' =>'required', 
	    ]);

		   $this->sem_cos->update(['weight_id' => $this->weight_id]);
		  
		$this->resetInputFields();
	}
	#Reset input field values
  private function resetInputFields(){
    $this->weight_id =  ''; 
  }

  public function render()
  { 
  	return view('livewire.erp.marks.add');
  }

  public function mount($semCos_id) 
  {
  	$this->weights = Weight::all();
  	$this->sem_cos = SemCourse::findOrFail($semCos_id);

  }
}

app/Http/Livewire/Erp/Marks/Create.php
<?php

namespace App\Http\Livewire\Erp\Marks;

use Livewire\Component;
use App\Regitration;
use App\Result;

class Create extends Component
{
    public $reg_id, $state;
    public $mark; // Receives Post Request values in an array 
 
    public function mount($reg_id, $state)
    {
        $this->reg_id = $reg_id;
        $this->state = $state;
    }

    public function save()
    {
        $this->validate([
            'mark' => 'required|between:0,100|regex:/^\d+(\.\d{1,2})?$/'
        ]);
        $result = new Result;
        $result->registration_id = $this->reg_id;    
        $result->{$this->state} = $this->mark; 
        $result->save(); 
        // $this->resetInputs(); 
    }


    public function render()
    {
        return view('livewire.erp.marks.create');
    }
}
 

app/Http/Livewire/Erp/Payments.php
<?php

namespace App\Http\Livewire\Erp;

namespace App\Http\Livewire\Erp;

use Livewire\Component;
use Illuminate\Validation\Rule;
use Livewire\WithPagination;
use App\Payment;

class Payments extends Component
{
    use WithPagination;
    public $perPage = 10;
    public $search = '';
    public $orderBy = 'id';
    public $orderAsc = 'asc';
    public $data = [], $payment_id =0;


   public function render()
    {       
        # Get all the payments
        $payments = Payment::search($this->search)
                            ->orderBy($this->orderBy, $this->orderAsc)
                            ->paginate($this->perPage); 
        return view('livewire.erp.payments.index', ['payments' => $payments]);
    }

}

resources/views/livewire/erp/faculties/create.blade.php
<div>
  <!--Title-->
  <form wire:submit.prevent="store" class="px-4"> 
    <p class="text-blue-500 text-xl font-bold text-center mt-1">Enter New Faculty</p>
      <div class="md:w-4/20 px-3 mb-2 mt-8 md:mb-0">
        <label class="block uppercase tracking-wide text-blue-800 text-sm font-bold mb-2 mt-8">Code</label>
        <input type="text" wire:model.lazy="data.code" class=" appearance-none block w-full text-blue-700 border border-blue-200 rounded py-1 px-6 mb-3 leading-tight focus:outline-none focus:bg-white">
         @error('data.code')       
            <p class="text-red-500 text-sm italic">
                {{ $message }}
            </p>
            @enderror
      </div>
      <div class="md:w-4/20 px-3 mb-2 mt-8 md:mb-0">
        <label class="block uppercase tracking-wide text-blue-800 text-sm font-bold mb-2 mt-8">Name</label>
        <input type="text" wire:model.lazy="data.name" class=" appearance-none block w-full text-blue-700 border border-blue-200 rounded py-1 px-6 mb-3 leading-tight focus:outline-none focus:bg-white">
         @error('data.name')       
            <p class="text-red-500 text-sm italic">
                {{ $message }}
            </p>
            @enderror
      </div>
      <!--Footer-->
      <div class="flex justify-center mb-4 pt-2">
        <button class="bg-white border border-blue-200 text-blue-400 p-1 rounded-lg hover:text-white hover:bg-indigo-400">Submit</button>
      </div>
  </form>
</div>

resources/views/livewire/erp/faculties/edit.blade.php
<div>
  <!--Title-->
  <form wire:submit.prevent="store" class="px-4"> 
    <p class="text-blue-500 text-xl font-bold text-center mt-1">Enter New Department</p> <div class="md:w-4/20 px-3 mb-2 mt-8 md:mb-0">
        <label class="block uppercase tracking-wide text-blue-800 text-sm font-bold mb-2 mt-8">Code</label>
        <input type="text" wire:model.lazy="data.code" class=" appearance-none block w-full text-blue-700 border border-blue-200 rounded py-1 px-6 mb-3 leading-tight focus:outline-none focus:bg-white">
         @error('data.code')       
            <p class="text-red-500 text-sm italic">
                {{ $message }}
            </p>
            @enderror
      </div>
      <div class="md:w-4/20 px-3 mb-2 mt-8 md:mb-0">
        <label class="block uppercase tracking-wide text-blue-800 text-sm font-bold mb-2 mt-8">Name</label>
        <input type="text" wire:model.lazy="data.name" class=" appearance-none block w-full text-blue-700 border border-blue-200 rounded py-1 px-6 mb-3 leading-tight focus:outline-none focus:bg-white">
         @error('data.name')       
            <p class="text-red-500 text-sm italic">
                {{ $message }}
            </p>
            @enderror
      </div>
      @if($isEdit == 1)
      <div class="md:w-4/20 px-3 mb-2 mt- md:mb-0">
        <label class="block uppercase tracking-wide text-blue-800 text-sm font-bold mb-2 mt-8">Dean</label>
        <select wire:model.lazy="dean_id" name="dean_id" class="block w-full text-blue-700 border border-blue-200 py-1 px-6 mb-3 rounded leading-tight focus:outline-none focus:bg-white">
          
           <option value="">Select</option>
           @foreach($deans as $dean)
           <option @if(old('dean_id') == $dean->id) selected @endif value="{{$dean->id}}">{{$dean->full_name }}</option>
           @endforeach
        </select>          
          @error('data.dean_id')         
              <p class="text-red-500 text-sm italic">
                  {{ $message }}
              </p>
          @enderror
        </div>
        @endif
      <!--Footer-->
      <div class="flex justify-center mb-4 pt-2">
        <button class="bg-white border border-blue-200 text-blue-400 p-1 rounded-lg hover:text-white hover:bg-indigo-400">Submit</button>
      </div>
  </form>
</div>

resources/views/livewire/erp/faculties/index.blade.php
<div class="min-w-full">  
  <div class="py-4 flex flex-row mb-4 min-w-full">
  	<div class="w-1/6 flex flex-row">
  		<div class="flex flex-row"> 
          @if(auth()->user()->hasPermission('faculties.admin'))
         <div class="mx-5">
			    <div x-data="{ 'showModal': false }" @eModal.window="showModal = true" @keydown.escape="showModal = false"  x-cloak>
			      <button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white p-0 hover:border-transparent rounded "><a href="#" @click.prevent="showModal = true" wire:click="create"><x-zondicon-add-outline class="h-6 w-6"/></a></button>
			        <!-- overlay -->
			      <div class="overflow-auto" style="background-color: rgba(0,0,0,0.5)" x-show="showModal" :class="{ 'absolute inset-0 z-10 flex items-center justify-center': showModal }">
			              <!--Dialog-->
			        <div class="bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg relative text-left " x-show="showModal" @click.away="showModal = false" >

		          <button class="absolute top-0 right-0 mr-2 text-red-500" type="button" @click="showModal = false">✖</button> 
			      @include('livewire.erp.faculties.create')
			        </div>
			      </div>
			    </div>
			    @else    
			    <button class="bg-transparent text-gray-400 font-semibold border border-gray-400 py-2 px-2 rounded "><a href="#"><x-zondicon-add-outline class="h-4 w-4"/></a></button>
		       @endif 
		    </div>
		    <div>
		          @if(auth()->user()->hasPermission('faculties.admin'))
			    <div x-data="{ 'showModal': false }" @eModal.window="showModal = true" @keydown.escape="showModal = false"  x-cloak>
			      <button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white p-0 hover:border-transparent rounded "><a href="#" @click.prevent="showModal = true" wire:click="createD"><x-zondicon-load-balancer class="h-6 w-6"/></a></button>
			        <!-- overlay -->
			      <div class="overflow-auto" style="background-color: rgba(0,0,0,0.5)" x-show="showModal" :class="{ 'absolute inset-0 z-10 flex items-center justify-center': showModal }">
			              <!--Dialog-->
			        <div class="bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg relative text-left " x-show="showModal" @click.away="showModal = false" >

		          <button class="absolute top-0 right-0 mr-2 text-red-500" type="button" @click="showModal = false">✖</button> 
			      @include('livewire.erp.faculties.d_create')
			        </div>
			      </div>
			    </div>
			    @else    
			    <button class="bg-transparent text-gray-400 font-semibold border border-gray-400 py-2 px-2 rounded "><a href="#"><x-zondicon-load-balancer class="h-4 w-4"/></a></button>
		       @endif 
		     </div>
	     </div>
    </div>

    <div class="relative w-5/6 flex flex-row-reverse ">
	    <div class="relative text-gray-800 mr-4 order-4">
        <select wire:model="orderBy" class="block appearance-none w-full bg-grey-200 border border-grey-200 text-grey-darker py-1 rounded leading-tight pr-5 pl-2 focus:outline-none focus:bg-white focus:border-yellow-500">
	        <option value="name">Name</option>
	        <option value="code">Code</option>
	        <option value="dean_id">Faculty</option>
        </select>
        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center text-grey-darker">
        	<x-zondicon-cheveron-down class="h-4 w-4"/>
      	</div>        
	    </div> 
	    <div class="relative text-gray-800 mr-4 order-3">
	      <select wire:model="orderAsc" class="bg-white border border-blue-100 text-blue-800 py-1 pr-4 pl-2 rounded leading-tight focus:outline-none focus:bg-white focus:border-yellow-500 appearance-none">
	        <option value="asc">Ascending</option>
	        <option value="desc">Descending</option>
        </select>
        <div class="pointer-events-none absolute inset-y-0 right-0 p-1 text-grey-darker leading-tight mt-1 ml-3">
        <x-zondicon-cheveron-down class="h-4 w-4"/>
      </div>        
	    </div>
	    <div class="relative text-gray-800 mr-4 order-2">
	      <select wire:model="perPage" class="bg-white border border-blue-100 text-blue-800 py-1 pl-2 pr-2 rounded leading-5 focus:outline-none focus:bg-white focus:border-yellow-500 appearance-none ">
	        <option>10</option>
	        <option>25</option>
	        <option>50</option>
	        <option>75</option>
	        <option>100</option>
	        <option>200</option>
        </select>	
        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center text-grey-darker">
        <x-zondicon-cheveron-down class="h-4 w-4"/>
      </div>          
	    </div> 
	    <div class="text-gray-800 relative order-1">
	      <input type="search" wire:model.debounce.300ms="search" placeholder="Search" class="bg-white p-1 rounded-full text-sm focus:outline-none">
	      <button class="absolute inset-y-0 right-0 mx-2">
	        <x-zondicon-search class="h-4 w-4"/>
	      </button>
	    </div>
	  </div>
	</div>
  <div class="bg-white overflow-auto">
    <table class="min-w-full bg-white">
      <thead class="bg-sidebar text-white">
        <tr>
          <th class="text-left py-1 px-4 uppercase font-semibold text-sm">Faculty</th>
          <th class="text-left py-1 px-4 uppercase font-semibold text-sm">Dean</th>
          <th class="text-left py-1 px-4 uppercase fon t-semibold text-sm">Options</th>
        </tr>
      </thead>
      <tbody class="text-gray-700 divide-y-2 divide-red-100 divide-dotted">
         @foreach($faculties as $faculty)
        @if($loop->iteration % 2 == 1)@php $bg =''; @endphp @else @php $bg ='bg-purple-100'; @endphp @endif
        <tr class="theme-text {{$bg}}">
          <td class="text-left py-1 px-4"> {{ $faculty->full_name }} </td>
          <td class="text-left py-1 px-4">@if($faculty->dean_id > 0) {{ $faculty->current->full_name}} @endif</td>
          <td class="text-left py-1 px-4 flex flex-row"> 
          	 @if(auth()->user()->hasPermission('faculties.admin'))
		    <div x-data="{ 'showModal': false }" @keydown.escape="showModal = false">
		      <button class="bg-transparent hover:bg-yellow-800 text-yellow-800 font-semibold hover:text-white p-0 hover:border-transparent rounded mr-4 "><a href="#" @click="showModal = true" wire:click="edit({{$faculty->id}})"><x-zondicon-edit-pencil class="h-4 w-4"/></a></button>
		        <!-- overlay -->
		      <div class="overflow-auto" style="background-color: rgba(0,0,0,0.5)" x-show="showModal" :class="{ 'absolute inset-0 z-10 flex items-center justify-center': showModal }" x-cloak>
		              <!--Dialog-->
		        <div class="bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg relative text-left " x-show="showModal" @click.away="showModal = false" >
    
              <button class="absolute top-0 right-0 mr-2 text-red-500" type="button" @click="showModal = false">✖</button> 
		      @include('livewire.erp.faculties.edit')
		        </div>
		      </div>
		    </div>
		    @else    
		    <button class="bg-transparent text-gray-400 font-semibold border border-gray-400 py-2 px-2 rounded "><a href="#"><x-zondicon-edit-pencil class="h-4 w-4"/></a></button>
	       @endif 
	        @if(auth()->user()->hasPermission('faculties.admin'))    
		    <button class="bg-transparent hover:bg-red-500 text-red-500 font-semibold hover:text-white p-0 hover:border-transparent rounded" wire:click.prevent="delete({{$faculty->id}})"><a href="#"><x-zondicon-trash class="h-4 w-4"/></a></button>
	       @endif
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
 {!! $faculties->links('vendor.pagination.tailwind_live') !!} 
	</div>
</div>